spring:

  datasource:
        url: jdbc:postgresql://localhost:5433/samurai
        username: samurai
        password: password
        driver-class-name: org.postgresql.Driver

  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

server:
  port: 8081
