spring:
  datasource:
    username: hunters_league
    password:
  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only
  jpa:
      properties:
        hibernate:
        default_schema: public
  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml